# Generated by Django 5.1.1 on 2024-10-16 03:04

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "rooming_status",
                    models.CharField(
                        choices=[
                            (0, "Not looking for housing"),
                            (1, "Looking for housing"),
                            (2, "Have housing plans and looking for roommate(s)"),
                        ],
                        max_length=200,
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="")),
                ("bio", models.CharField(max_length=3000)),
                ("school", models.TextField()),
                ("date_of_birth", models.DateField(editable=False)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (0, "Freshman Undergraduate"),
                            (1, "Sophomore Undergraduate"),
                            (2, "Junior Undergraduate"),
                            (3, "Senior Undergraduate"),
                            (4, "Fifth-year Undergraduate"),
                            (5, "Graduate Student"),
                        ]
                    ),
                ),
                (
                    "phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=300, region=None
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[
                            (0, "Male"),
                            (1, "Female"),
                            (2, "Transmale"),
                            (3, "Transfemale"),
                            (4, "Neutral/Other"),
                            (5, "Prefer not to say"),
                        ]
                    ),
                ),
                ("dietary_restrictions", models.CharField(blank=True, max_length=200)),
                (
                    "sleep_time_weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Before 9:00 PM"),
                            (1, "Between 9:00 PM and 11:00 PM"),
                            (2, "Between 11:00 PM and 1:00 AM"),
                            (3, "After 1:00 AM"),
                        ]
                    ),
                ),
                (
                    "sleep_time_weekend",
                    models.IntegerField(
                        choices=[
                            (0, "Before 9:00 PM"),
                            (1, "Between 9:00 PM and 11:00 PM"),
                            (2, "Between 11:00 PM and 1:00 AM"),
                            (3, "After 1:00 AM"),
                        ]
                    ),
                ),
                (
                    "wake_time_weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Before 7:00 AM"),
                            (1, "Between 7:00 AM and 9:00 AM"),
                            (2, "Between 9:00 AM and 11:00 AM"),
                            (3, "After 11:00 AM"),
                        ]
                    ),
                ),
                (
                    "wake_time_weekend",
                    models.IntegerField(
                        choices=[
                            (0, "Before 7:00 AM"),
                            (1, "Between 7:00 AM and 9:00 AM"),
                            (2, "Between 9:00 AM and 11:00 AM"),
                            (3, "After 11:00 AM"),
                        ]
                    ),
                ),
                ("animals", models.CharField(blank=True, max_length=100)),
                ("additional_notes", models.CharField(blank=True, max_length=2000)),
                ("pref_same_gender", models.BooleanField(default=True)),
                ("pref_smoking", models.BooleanField(default=False)),
                (
                    "pref_cleaniness",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "I prefer my living space to be neat and clean all of the time",
                            ),
                            (
                                1,
                                "I like my living space to be clean but I can tolerate some clutter",
                            ),
                            (2, "Mess/clutter does not bother me"),
                        ]
                    ),
                ),
                (
                    "pref_temperature",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "I prefer a relatively warm temperature (above 72F/22C)",
                            ),
                            (
                                1,
                                "I prefer a relatively cool temperature (below 68F/20C)",
                            ),
                            (2, "No preference"),
                        ]
                    ),
                ),
                ("pref_age_min", models.IntegerField(blank=True)),
                ("pref_age_max", models.IntegerField(blank=True)),
                (
                    "pref_day_guests",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "Guests should always be coordinated to make sure everyone is comfortable.",
                            ),
                            (
                                1,
                                "Let's talk together about what rules we want to set about guests coming over.",
                            ),
                            (
                                2,
                                "Spontaneity is great! Anything (within reason) is fine by me.",
                            ),
                        ]
                    ),
                ),
                (
                    "pref_night_guests",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "Guests should always be coordinated to make sure everyone is comfortable.",
                            ),
                            (
                                1,
                                "Let's talk together about what rules we want to set about guests coming over.",
                            ),
                            (
                                2,
                                "Spontaneity is great! Anything (within reason) is fine by me.",
                            ),
                        ]
                    ),
                ),
                ("pref_animals", models.BooleanField(default=True)),
                (
                    "pref_sleep_light",
                    models.IntegerField(
                        choices=[
                            (0, "Lights on"),
                            (1, "Some minimal light"),
                            (2, "Completely dark"),
                            (3, "No preference"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
