# Generated by Django 5.0.6 on 2024-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_tiny_rename_pref_cleaniness_member_pref_cleanliness_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tiny",
        ),
        migrations.AddField(
            model_name="member",
            name="city_name",
            field=models.CharField(default="Boston", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="private_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="state_name",
            field=models.CharField(
                default="Massachussetts",
                error_messages={
                    "max_length": "State names must be two letter abbreviations."
                },
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
