# Generated by Django 5.0.6 on 2024-11-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_delete_tiny_member_city_name_member_private_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="first_name",
            field=models.CharField(default="Josephine", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="last_name",
            field=models.CharField(default="Wang", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(default="fullstackpassword", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(default="josiexw", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
