# Generated by Django 5.0.6 on 2024-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_member_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
