# Generated by Django 5.0.6 on 2025-05-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_member_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="profile_pic",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="animals",
            field=models.BooleanField(default=False),
        ),
    ]
