# Generated by Django 5.0.6 on 2025-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_member_profile_pic_alter_member_animals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_pic",
            field=models.TextField(),
        ),
    ]
