# Generated by Django 5.0.6 on 2025-05-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_member_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.IntegerField(
                choices=[
                    (0, "Male"),
                    (1, "Female"),
                    (2, "Trans male"),
                    (3, "Trans female"),
                    (4, "Neutral/Other"),
                    (5, "Prefer not to say"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="pref_age_max",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="pref_age_min",
            field=models.IntegerField(),
        ),
    ]
