# Generated by Django 5.0.6 on 2025-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_member_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="pref_age_max",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="pref_age_min",
            field=models.IntegerField(),
        ),
    ]
