# Generated by Django 5.0.6 on 2025-04-30 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_member_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProspectiveListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("address", models.CharField(max_length=500)),
                ("housing_image_base64", models.TextField(blank=True, null=True)),
                ("contact_info", models.CharField(max_length=200)),
                ("num_bedrooms", models.PositiveIntegerField()),
                ("num_bathrooms", models.PositiveIntegerField()),
                ("has_ac", models.BooleanField(default=False)),
                ("has_wifi", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("num_roommates_needed", models.PositiveIntegerField()),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "poster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospective_listings",
                        to="accounts.member",
                    ),
                ),
            ],
        ),
    ]
