# Generated by Django 5.1.7 on 2025-04-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivestay',
            name='aboutText',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
