# Generated by Django 5.0.6 on 2025-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospectivelisting",
            name="city",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospectivelisting",
            name="state",
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
